name: ci

# This is a real hack but we need a "passing" workflow to
# allow the status checks on the PR to work

on:
  push:
    branches:     [ master ]
    paths-ignore: [ apis/poi/** ]
  pull_request:
    branches:     [ master ]
    paths-ignore: [ apis/poi/** ]

jobs:     
  build:   
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
