name: All Other Files Workflow

# This is a real hack but we need a "passing" workflow to
# allow the status checks on the PR to work

on:
  push:
    branches:     [ master ]
    paths-ignore: [ apis/poi/**, apis/userprofile/** ]
  pull_request:
    branches:     [ master ]
    paths-ignore: [ apis/poi/**, apis/userprofile/** ]

jobs:     
  build:
    name: Build and test   
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:    
      - name: Cleanup
        run: echo "Pass as no checks required."
