name: POI API Workflow

on:
  push:
    branches: [ master ]
    paths: [ apis/poi/** ]
  pull_request:
    branches: [ master ]
    paths: [ apis/poi/** ]

env:
  wd_path: apis/poi
  repo_url: docker.pkg.github.com
  resource_group: openhackpf79scm7rg
  webapp_name: openhackpf79scm7poi
  staging_name: openhackpf79scm7poi-staging
  api_name: api-poi
  healthcheck_path: azurewebsites.net/api/healthcheck/poi

jobs:     
  build:   
    runs-on: ubuntu-latest
    name: Build and test
    defaults:
      run:
        working-directory: ${{ env.wd_path }}    

    steps:    
      - uses: actions/checkout@v2
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        #with:
          #dotnet-version: 2.1.x

      - name: Install dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build --configuration Release --no-restore
      
      - name: Test
        run: dotnet test --no-restore --verbosity normal
        
  log_issue:
    if: failure()
    runs-on: ubuntu-latest
    
    steps:
      - name: Create issue when failed
        id: create-issue
        uses: JasonEtco/create-an-issue@v2
        with:
          filename: .github/ISSUE_TEMPLATE/bug_report.md        
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          name: Build failed
          title: The build failed for ${{ github.workflow }}
             
      - name: Log issue number
        run: 'echo Created issue number ${{ steps.create-issue.outputs.number }}'

  push_to_registry:
    if: github.ref == 'refs/heads/master'
    needs: [build]
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.wd_path }}/web   
           
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Login to package registry
        run: docker login ${{ env.repo_url }} -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
        
      - name: Build docker image
        run: docker build -t ${{ env.repo_url }}/${{ github.repository }}/${{ env.api_name }}:${{ github.run_number }} .

      - name: Push to registry
        run: docker push ${{ env.repo_url }}/${{ github.repository }}/${{ env.api_name }}:${{ github.run_number }}

  deploy:
    needs: [push_to_registry]
    name: Deploy to staging
    runs-on: ubuntu-latest    

    steps:
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} 

      - run: |
          az webapp config container set \
            --docker-registry-server-url https://${{ env.repo_url }} \
            --docker-registry-server-user ${{ github.actor }} \
            --docker-registry-server-password ${{ secrets.PACKAGESPAT }} \
            --resource-group ${{ env.resource_group }} \
            --name ${{ env.staging_name }}

      - uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.staging_name }}
          publish-profile: ${{ secrets.POIWEBAPPPUBLISHPROFILE }}
          images: '${{ env.repo_url }}/${{ github.repository }}/${{ env.api_name }}:${{ github.run_number }}'

  check-staging:
    needs: [deploy]
    runs-on: ubuntu-latest  
    name: Run healthcheck on staging 
    timeout-minutes: 3

    steps:
      - name: Wait on
        uses: iFaxity/wait-on-action@v1
        with:
          resource: https://${{ env.staging_name }}.${{ env.healthcheck_path }}
          interval: 5000
          
      - name: Healthcheck
        run: |
          RESPONSE=$(curl https://${{ env.staging_name }}.${{ env.healthcheck_path }} --silent --header 'Accept: application/json') 
          #RESULT=$(echo $RESPONSE | python3 -c 'import sys, json; print(json.load(sys.stdin)[\'status\'])')
          if [[ -z $RESPONSE ]]; then exit 1; fi

  switch-staging-production:
    needs: [check-staging]
    runs-on: ubuntu-latest  
    name: Swap staging to production 

    steps:
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} 

      - run: |
          az webapp deployment slot swap \
            --slot staging \
            --target-slot production \
            --resource-group ${{ env.resource_group }} \
            --name ${{ env.webapp_name }} 

  check-production:
    needs: [switch-staging-production]
    runs-on: ubuntu-latest  
    name: Run healthcheck on production 

    steps:        
      - name: Healthcheck
        run: |
          RESPONSE=$(curl https://${{ env.webapp_name }}.${{ env.healthcheck_path }} --silent --header 'Accept: application/json') 
          #RESULT=$(echo $RESPONSE | python3 -c 'import sys, json; print(json.load(sys.stdin)[\'status\'])')
          if [[ -z $RESPONSE ]]; then exit 1; fi

  rollback:
    needs: [switch-staging-production, check-production]
    if: failure()
    runs-on: ubuntu-latest  
    name: Rollback production

    steps:
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} 

      - run: |
          az webapp deployment slot swap \
            --slot staging \
            --target-slot production \
            --resource-group ${{ env.resource_group }} \
            --name ${{ env.webapp_name }} 




