name: Test Publish Workflow

env:
  wd_path: apis/poi
  repo_url: docker.pkg.github.com
  resource_group: openhackpf79scm7rg
  webapp_name: openhackpf79scm7poi
  staging_name: openhackpf79scm7poi-staging
  api_name: api-poi
  healthcheck_path: azurewebsites.net/api/healthcheck/poi

on:
  workflow_dispatch:

jobs:

  bashtest:
    runs-on: ubuntu-latest  
    steps:
      - run: |
          echo 'Hello'
          sudo apt install jq
          RESPONSE=$(curl https://${{ env.staging_name }}.${{ env.healthcheck_path }} --silent --header 'Accept: application/json')

  switch-staging-production:
    if: ${{ !always() }}
    runs-on: ubuntu-latest  `
    name: Swap staging to production 

    steps:
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} 

      - run: |
          az webapp deployment slot swap \
            --slot staging \
            --target-slot production \
            --resource-group ${{ env.resource_group }} \
            --name ${{ env.webapp_name }} 
             
  check:
    if: ${{ !always() }}
    runs-on: ubuntu-latest  
    name: Run healthcheck on staging 
    timeout-minutes: 3

    steps:
      - name: Wait on
        uses: iFaxity/wait-on-action@v1
        with:
          resource: https://${{ env.staging_name }}.${{ env.healthcheck_path }}
          interval: 5000
          
      - name: Healthcheck
        run: |
          RESPONSE=$(curl https://${{ env.staging_name }}.${{ env.healthcheck_path }} --silent --header 'Accept: application/json') 
          #RESULT=$(echo $RESPONSE | python3 -c 'import sys, json; print(json.load(sys.stdin)[\'status\'])')
          if [[ $RESPONSE != 'Healthy' ]]; then exit 1; fi
