name: User Profile Workflow

on:
  push:
    branches: [ master ]
    paths: [ apis/userprofile/** ]
  pull_request:
    branches: [ master ]
    paths: [ apis/userprofile/** ]

env:
  wd_path: apis/userprofile
  repo_url: docker.pkg.github.com
  resource_group: openhackpf79scm7rg
  webapp_name: openhackpf79scm7userprofile
  staging_name: openhackpf79scm7userprofile-staging
  api_name: api-userprofile
  healthcheck_path: azurewebsites.net/api/healthcheck/user
  
jobs:     
  build:   
    runs-on: ubuntu-latest
    name: Build and test
    defaults:
      run:
        working-directory: ${{ env.wd_path }}
        
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.3
        #with:
          # Set always-auth in npmrc
          #always-auth: # optional, default is false
          # Version Spec of the version to use.  Examples: 10.x, 10.15.1, >=10.15.0
          #node-version: # optional, default is 10.x
          # Optional registry to set up for auth. Will set the registry in a project level .npmrc and .yarnrc file, and set up auth to read in from env.NODE_AUTH_TOKEN
          #registry-url: # optional
          # Optional scope for authenticating against scoped registries
          #scope: # optional
          # Deprecated. Use node-version instead. Will not be supported after October 1, 2019
          #version: # optional

      - run: npm install

      - run: npm run build --if-present

      - run: npm test

  log_issue:
    if: failure()
    runs-on: ubuntu-latest
    
    steps:
      - name: Create issue when failed
        id: create-issue
        uses: JasonEtco/create-an-issue@v2
        with:
          filename: .github/ISSUE_TEMPLATE/bug_report.md        
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          name: Build failed
          title: The build failed for ${{ github.workflow }}
             
      - name: Log issue number
        run: 'echo Created issue number ${{ steps.create-issue.outputs.number }}'

  push_to_registry:
    if: github.ref == 'refs/heads/master'
    needs: [build]
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.wd_path }}
                   
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Login to package registry
        run: docker login ${{ env.repo_url }} -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
        
      - name: Build docker image
        run: docker build -t ${{ env.repo_url }}/${{ github.repository }}/${{ env.api_name }}:${{ github.run_number }} .

      - name: Push to registry
        run: docker push ${{ env.repo_url }}/${{ github.repository }}/${{ env.api_name }}:${{ github.run_number }}

  deploy:
    needs: [push_to_registry]
    name: Deploy to staging
    runs-on: ubuntu-latest    

    steps:
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} 

      - run: |
          az webapp config container set \
            --docker-registry-server-url https://${{ env.repo_url }} \
            --docker-registry-server-user ${{ github.actor }} \
            --docker-registry-server-password ${{ secrets.PACKAGESPAT }} \
            --resource-group ${{ env.resource_group }} \
            --slot staging \
            --name ${{ env.webapp_name }}

      - uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.webapp_name }}
          slot-name: staging
          publish-profile: ${{ secrets.USERPROFILEWEBAPPSTAGINGPUBLISHPROFILE }}
          images: '${{ env.repo_url }}/${{ github.repository }}/${{ env.api_name }}:${{ github.run_number }}'

  check-staging:
    needs: [deploy]
    runs-on: ubuntu-latest  
    name: Run healthcheck on staging 
    timeout-minutes: 3

    steps:
      - name: Wait on
        uses: iFaxity/wait-on-action@v1
        with:
          resource: https://${{ env.staging_name }}.${{ env.healthcheck_path }}
          interval: 5000
          
      - name: Healthcheck
        run: |
          RESPONSE=$(curl https://${{ env.staging_name }}.${{ env.healthcheck_path }} --silent --header 'Accept: application/json') 
          RESULT=$(echo $RESPONSE | jq '.status')
          if [[ ! $RESULT = \"Healthy* ]]; then exit 1; fi          

  switch-staging-production:
    needs: [check-staging]
    runs-on: ubuntu-latest  
    name: Swap staging to production 

    steps:
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} 

      - run: |
          az webapp deployment slot swap \
            --slot staging \
            --target-slot production \
            --resource-group ${{ env.resource_group }} \
            --name ${{ env.webapp_name }} 

  check-production:
    needs: [switch-staging-production]
    runs-on: ubuntu-latest  
    name: Run healthcheck on production 

    steps:        
      - name: Healthcheck
        run: |
          RESPONSE=$(curl https://${{ env.webapp_name }}.${{ env.healthcheck_path }} --silent --header 'Accept: application/json') 
          RESULT=$(echo $RESPONSE | jq '.status')
          if [[ ! $RESULT = \"Healthy* ]]; then exit 1; fi 

  rollback:
    needs: [switch-staging-production, check-production]
    runs-on: ubuntu-latest  
    name: Rollback on fail, stop staging on success

    steps:
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} 

      - name: Failure - swap staging back to production
        if: failure()
        run: |
          az webapp deployment slot swap \
            --slot staging \
            --target-slot production \
            --resource-group ${{ env.resource_group }} \
            --name ${{ env.webapp_name }} 

      - name: Success - stop staging slot
        if: success()
        run: |
          az webapp stop \
            --slot staging \
            --resource-group ${{ env.resource_group }} \
            --name ${{ env.webapp_name }} 



