name: User Profile Workflow

on:
  push:
    branches: [ master ]
    paths:    [ apis/userprofile/** ]
  pull_request:
    branches: [ master ]
    paths:    [ apis/userprofile/** ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apis/userprofile  
        
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.3
        #with:
          # Set always-auth in npmrc
          #always-auth: # optional, default is false
          # Version Spec of the version to use.  Examples: 10.x, 10.15.1, >=10.15.0
          #node-version: # optional, default is 10.x
          # Optional registry to set up for auth. Will set the registry in a project level .npmrc and .yarnrc file, and set up auth to read in from env.NODE_AUTH_TOKEN
          #registry-url: # optional
          # Optional scope for authenticating against scoped registries
          #scope: # optional
          # Deprecated. Use node-version instead. Will not be supported after October 1, 2019
          #version: # optional

      - run: npm install

      - run: npm run build --if-present

      - run: npm test
        env:
          CI: true

